name: CI

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  testAPI:

      runs-on: ubuntu-latest
      environment: DEV
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '22'
            cache: 'maven'
        - run: mvn clean compile
        - run: echo "${{ vars.ENV_FILE }}" >> .env
        - run: mvn test

  notification:
    if: always()
    needs: [ testAPI ]

    runs-on: ubuntu-latest
    steps:
      - run: |
          curl --request POST \
               --url https://api.telegram.org/bot${{ secrets.TEST_TELEGRAM_TOKEN }}/sendMessage \
               --header 'Content-Type: application/json' \
                --data '{ "chat_id": "${{ secrets.TEST_TELEGRAM_CHAT_ID }}", "text": "Report link: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" }'