name: CI

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: 0 9 * * *

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  testAPI:

      runs-on: ubuntu-latest
      environment: TEST
      steps:
        - uses: actions/checkout@v6
        - uses: actions/setup-java@v5
          with:
            distribution: 'temurin'
            java-version: '22'
            cache: 'maven'
        - run: mvn clean compile
        - run: echo "LOGIN_AUTH=${{ secrets.LOGIN_AUTH }}" >> .env
        - run: echo "PASSWORD_AUTH=${{ secrets.PASSWORD_AUTH }}" >> .env
        - run: echo "BASE_URL=${{ vars.BASE_URL }}" >> .env
        - name: Тест
          run: |
            if [[ "${{ github.event_name  }}" == "schedule" ]]; then
              mvn clean test -Dgroups="regression"
            else
              mvn clean test 
            fi
        - name: Load previous report history
          uses: actions/checkout@v6
          if: always()
          continue-on-error: true
          with:
            ref: gh-pages
            path: gh-pages
        - name: Build Allure report
          uses: allegro/allure-report-action@v1
          if: always()
          id: allure-report
          with:
            report_path: allure-report
            results_path: target/allure-results
        - name: Check allure results
          if: always()
          run: |
            ls -la target/allure-results/ || echo "No allure-results found"
        - name: Deploy report to GitHub Pages
          uses: peaceiris/actions-gh-pages@v4
          if: ${{ always() && steps.allure-report.outcome == 'success' }}
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_branch: gh-pages
            publish_dir: allure-history

  notification:
    if: always()
    needs: [ testAPI ]

    runs-on: ubuntu-latest
    steps:
      - name: Отправка уведомления в Telegram
        run: |
          if [[ "${{ needs.testAPI.result }}" == "success" ]]; then
            STATUS="✔️ Успех"
          else
            STATUS="😒 Провалилось :-("
          fi
          
          MESSAGE="${STATUS} \nReport link: https://dania13.github.io/java-test-QA/}"  
          
              # Экранируем для JSON: кавычки, слеши, переносы строк
          ESCAPED=$(echo "$MESSAGE" | jq -R -s '.')
          
          curl --request POST \
            --url https://api.telegram.org/bot${{ secrets.TEST_TELEGRAM_TOKEN }}/sendMessage \
            --header 'Content-Type: application/json' \
            --data "{\"chat_id\": \"${{ secrets.TEST_TELEGRAM_CHAT_ID }}\", \"text\": $ESCAPED"